POST http://localhost:8080/events
Content-Type: application/json

{
    "name": "Test event 2",
    "description": "This is a test event",
    "location": "Test location",    
    "dateTime": "2025-01-01T15:00:00Z"
}